### ISSUE TITLE
Development is stale

### ISSUE THREAD

**Issue by heltonbiker** [david672orford/GPX_Trip_Planner#1]
I am developing a [quite similar application to this one](https://github.com/heltonbiker/MapComplete) (only in PyQt, and focused in KML instead of GPX for now), and I have noticed you have made some remarkable progresses.

As such, I would like to know if you ever plan to keep developing something along the lines of a "desktop map-based trip planner", because if so, we could exchange some ideas.

Thanks @david672orford, and sorry if I'm being intrusive :o)

**Comment by david672orford** [comment]
This is the program which I use for viewing and editing GPX files and for trip planning. I wrote it because while many programs could import and export GPX files, I couldn't find anything which used GPX as its native format. I also wanted something I could hack on. I consider the core program finished. Changes nowadays are to to keep the data layers which it displays up-to-date and add new interesting sources.

As you say, the version on Github is stale. I have pushed the version which I now use.

I would be happy to exchange ideas with you.

**Comment by heltonbiker** [comment]
Thanks for your reply!

One question: when you say "the version on Github is stale" and "I pushed the version which I now use", do you mean the app is still developed elsewhere? Or do you mean that this version, although without recent changes, is the one you still use?

My main goal would be to exchange ideas about high-level operations (interactions, use-cases) that should belong to a good map-editor for home use and trip planning. Since we have distinct focus right now on our programs (Qt/Kml vs Gtk/Gpx), we can make the most of "things in common". One of my difficulties, and an important goal, would be to develop a good **data model**, and possibly a toolkit-independent _application library_, both in pure python. Those libraries could provide a good framework for both applications, for example.

By Data Model I mean: "ok, I'll open a GPX file... But open into _what_?" The same for a KML. Should there be a KML class? And what about converting one into another, like many applications do?

The way I see it, your "GeoDataModel" resides in `pykarta.geometry`, and you also have some other application-related classes and methods that I would like to contribute to, in `pykarta` library.

So if you have interest, we could restart the development of `pykarta`, what do you think?

Feel free to contact me privately at heltonbiker at gmail dot com, or via Issues if you don't mind.

**Comment by david672orford** [comment]
I think I should clear up some confusion. Development of GPX Trip Planner and Pykarta is not stale. It cannot be restarted because it was never stopped. It looked that way to you because I am the only developer and the only user. I had not bothered pushing changes to Github recently because nobody was showing any interest. I am glad you like the project. Thank you for reminding me to push changes.

The data model for GPX Trip Planner is in gpx_data_*.py. The part which represents a loaded GPX file is in gpx_data_gpx.py. It stores the objects in Gtk+ treestores and liststores.

There is indeed a data model in pykarta.geometry for representing geometric objects. It is used in a number of places including in the vector layer (maps/layers/vector.py) where the geometric primitives are wrapped into map layer objects. 

I am interested in porting PyKarta to Qt or more accurately in adding support for Qt. It would require a fair amount of work to abstract out some Gtk+ and Cairo stuff and provide Qt and QPainter replacements. Much of it is abstracted out already, but not everything.

How does QPainter compare to Cairo? Have you ever written a Qt widget in Python which draws itself using QPainter?

**Comment by heltonbiker** [comment]
Hi, David, thanks for your response!

First of all, now I understand what you meant regarding the development status. Like you, I'm also trying to scratch my own itch, so it's very stimulating to have someone to chat about this - and it looks that it's very hard to create a community about it, since everyone seems to be solving the problem in a slightly different but remarkably similar way.

I have taken a deeper look in your app, after getting everything to run and try a few examples. I loved the way your tiles load and resize (scaling up a lower-resolution version of a tile before painting over it with newer tiles), and the way you implemented the polygon drawing, specially the creation of two segments by dragging the midpoint of one - well, this is quite a standard already.

I plan to study all your code with more time, so that I can understand what features are available, how they relate to one another, and what's the overall architecture. Currently, at work, I develop with WPF (Visual Studio / C#) using the MVVM pattern, and we strive to keep a good architectural layering, separating "what should be in the model" and "what should be in the view". So we have packages named `DomainModel`, `ApplicationModels`, `Services`, `FeatureX`, `FeatureY`, and the like, always making sure the packages have high cohesion, low coupling and a healthy dependency structure. I plan to talk about these after getting familiar with Trip Planner.

Now regarding PyQt, while I still have a lot of ground to cover, I must say I'm amazed at how they created an incredible graphics API - and a much higher level than GTK and Cairo, IMO. The drawing APIs themselves are quite similar, with commands like "move_to", and "line_to" and "set_line_join" and everything that is similar across drawing APIs (including WPF graphics and Html Canvas context). So we cold say Cairo would be similar to QPainter in this sense.

What is a huge improvement, as I see it, is that you have the concept of a `Scene`, so the rendering is "retained" instead of "immediate". You add objects to the scene, and the rendering is managed by the view. Then you manipulate them in the scene (via mouse interaction through view events), and the scene is updated. You can even have lots of views to the same scene. In that sense, this poses a stark contrast to what you could do in Gtk/Cairo, at least considering the knowledge I have.
Other positive point of PyQt is that it's being currently developed, and the C++ docs are top-notch, while docs for cairo and gtk are rather old.

You can try to run [my current code](https://github.com/heltonbiker/MapComplete), and see how QPainter is used by QGraphicsItems to draw themselves. Just run `MapComplete.py` and you should see a slippy map with some continent borders, and following the code should be enough to have the gist of it. My present task is trying to properly model Kml content, so that I can open some file, and add the appropriate graphics wrapper to the MapScene (with styles and stuff, which I see you also have, inspired by Mapnik).

I won't have any time this weekend (gonna travel to visit my mother), but next week I plan to dedicate some quality time to this. As soon as I have something meaningful to start an activity, I can create a properly titled issue. In the meantime, feel free to write any questions or suggestions! :o)
